[package]
name = "rust-crypto"
version = "0.1.0"
authors = ["Bjarne H. Nielsen <bjarne@honil.dk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.0"
rstest = "0.5.2"
